DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER(
    ID BIGINT PRIMARY KEY  AUTO_INCREMENT,
    USER_NAME VARCHAR NOT NULL UNIQUE,
    USER_ID VARCHAR NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR NOT NULL UNIQUE,
    AGE INT NOT NULL
);